UI_BG = "#FFFFFF"
UI_CARD = "#FFFFFF"
UI_BORDER = "#D6E4F0"
UI_LINE = "#D6E4F0"
UI_PRIMARY = "#6BA3D6"
UI_PRIMARY_HOVER = "#5A94C7"
UI_PRIMARY_LIGHT = "#EEF4FB"
UI_BTN_BG = "#C5DCF0"
UI_BTN_HOVER = "#B0D0EC"
UI_BTN_TEXT = "#3A7AB0"
UI_BTN_PRIMARY_BG = "#5A94C7"
UI_BTN_PRIMARY_HOVER = "#4A84B7"
UI_BTN_PRIMARY_TEXT = "#FFFFFF"
UI_TEXT = "#1F2937"
UI_TEXT_MUTED = "#6B7280"

UI_FONT = ("Microsoft YaHei UI", 12)
UI_FONT_BOLD = ("Microsoft YaHei UI", 12, "bold")
UI_FONT_SMALL = ("Microsoft YaHei UI", 11)

ASPECT_WIDTH, ASPECT_HEIGHT = 16, 10
DEFAULT_WINDOW_WIDTH = 960
MIN_WINDOW_WIDTH = 800
